### ISSUE TITLE
Examples of Firebase Authentication

### ISSUE THREAD

**Issue by alltonp** [ThomasWeiser/elmfire#12]
Hi,

Thank you for elmfire, this looks like really nice.

I've been looking at your version of todomvc and I'm trying to understand how I might take that and add firebase authentication (which it seems you support).

Can you point to me to any example uses please, I'm not quite sure how to wire it all together...

Thanks

**Comment by ThomasWeiser** [comment]
I am sure you have seen the docs [here](http://package.elm-lang.org/packages/ThomasWeiser/elmfire/latest/ElmFire-Auth) at the package site.

Do you have a specific question?

Currently I am writing/contributing to an application called [The Plentiful Shop](https://github.com/plentiful/shop), which uses Firebase authentication. Here are the relevant code regions:
- [Login](https://github.com/plentiful/shop/blob/cca50f7fa1b2a532c1f2782cf7ebabe0d49e10f2/client/src/Components/Checkout.elm#L377-L384)
- [Create user](https://github.com/plentiful/shop/blob/cca50f7fa1b2a532c1f2782cf7ebabe0d49e10f2/client/src/Components/Checkout.elm#L391-L393)
- [Subscribe to auth state](https://github.com/plentiful/shop/blob/cca50f7fa1b2a532c1f2782cf7ebabe0d49e10f2/client/src/Components/Page.elm#L58-L63)
- [Use of auth state](https://github.com/plentiful/shop/blob/cca50f7fa1b2a532c1f2782cf7ebabe0d49e10f2/client/src/Components/Page.elm#L161-L176)

**Comment by alltonp** [comment]
Hi Thomas,

Thanks for responding. I have read the docs, but I couldn't see how to fit into my app. Being fairly new to Elm, I often find the package docs a little too abstract, nothing beats a simple complete example (like elmfire/example/src/Example.elm) that one can actually run and tweak. 

Sounds like The Plentiful Shop might have all the bits I need (and more), I will study that code.

Thank you

**Comment by ThomasWeiser** [comment]
Agreed, there should be a simple example for authentication. It's on my list.
