### ISSUE TITLE
Firebase 3.0

### ISSUE THREAD

**Issue by gz81gs** [ThomasWeiser/elmfire#14]
Does this library support Firebase_3.0 ?

**Comment by ThomasWeiser** [comment]
ElmFire currently uses Firebase's Web-API version 2.4.2.
This version [will continue to work](https://firebase.google.com/support/guides/firebase-web#update_your_client_version_numbered) against upgraded (_3.0_) projects.

Please also note that the database API didn't change in any way from version 2.4 to version 3.0. Only the authentication API did change a bit.

I am in the  [process](/ThomasWeiser/elmfire/issues/13) of updating ElmFire to Elm 0.17. I will probably switch to the new Firebase Web API, either on the initial or a subsequent release.

**Comment by StephenGrider** [comment]
Any progress on this, or any way that I can help?

**Comment by ThomasWeiser** [comment]
Continuing in #16
