### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by bstro** [ThomasWeiser/elmfire#3]
How is one supposed to consume this elm module? Admittedly, I am a noob. Try as I might, I cannot figure out how to use this with elm-package

**Comment by ThomasWeiser** [comment]
Thanks for the hint. The package is not yet published in the official catalog, so you cannot use `elm-package` to install it.

I've added a [section in the Readme](https://github.com/ThomasWeiser/elmfire#installation) how to install by cloning the github repo. I hope it's helpful.

Edit: In the process of publishing the package there is now a request for native code review: elm-lang/package.elm-lang.org#65
