### ISSUE TITLE
Synchronization of Dicts

### ISSUE THREAD

**Issue by thSoft** [ThomasWeiser/elmfire#4]
I know this is among the plans, but I'm creating an issue to signal that I'm interested in this feature, as well as for tracking the API design plans.

**Comment by thSoft** [comment]
The type signature I thought of at first stab:

``` elm
sync : Location -> Signal (Dict String Json.Encode.Value)
```

**Comment by ThomasWeiser** [comment]
Thanks for your participation in ElmFire!

I published a first, incomplete sketch in the branch [dict](/ThomasWeiser/elmfire/tree/dict).
This offers mirroring a Firebase object in a local `Dict String v`.

The all-in-one-function to use it is:

``` elm
mirror : Json.Decode.Decoder v -> Location -> (Task Error (), Signal (Dict String v))
```

Besides the desired signal it returns an initialization task that must be run to setup the mirroring.

There is a demonstration app in the directory `demo-dict`.

**Comment by thSoft** [comment]
Thank you, this is great! I'd have just one comment: the current implementation swallows JSON decoding errors. I propose to propagate them to the dictionary:

``` elm
mirror : Json.Decode.Decoder v -> Location -> (Task Error (), Signal (Dict String (Result String v)))
```

Then the client can do whatever it desires with the faulty entries (display the error, omit them etc.)

**Comment by ThomasWeiser** [comment]
I agree, decoding failures should be observable at some point.

Instead of forcing the `Dict` to have a value type of `Result String v` I would prefer to indicate failures with a special `Delta` value of `Undecodable String String`.

So to catch these errors one has to use the functions `subscribeDelta` and `integrate` instead of `mirror`.

Will update in branch [dict](/ThomasWeiser/elmfire/tree/dict)

**Comment by ThomasWeiser** [comment]
Implemented write operations. See demo for usage.

Later I intend to add also transactional operations (i.e. reading and writing, so both a decoder and an encoder is needed).

To summarize:

``` elm
type Delta v
  = Added String v
  | Changed String v
  | Removed String v
  | Idem
  | Undecodable String String

type Operation v
  = Empty
  | FromDict (Dict String v)
  | FromList (List (String, v))
  | Insert String v
  | Push v
  | Remove String
  | None

type Transaction v -- not implemented yet
  = None
  | Operation (Operation v)
  | Update String (Maybe v -> Maybe v)
  | Filter (String -> v -> Bool)
  | Map (String -> v -> v)
  | FilterMap (String -> v -> Maybe v)
  -- maybe more
```

**Comment by thSoft** [comment]
Awesome! So `mirror` is a convenience function, but if someone wants more control, `subscribeDelta` and a custom integrator function is needed (instead of `integrate` because it folds with `update` in a fixed way).

**Comment by thSoft** [comment]
I'd have one more consideration: IMHO `mirror` should return a record instead of a tuple to be more descriptive. What do you think?

**Comment by ThomasWeiser** [comment]
That sounds reasonable, thank you.

**Comment by thSoft** [comment]
I have one more use case. Let's suppose that we don't know initially where all our objects are but we want to load the object graph "lazily" according to the cross-references starting from one root object (perhaps across multiple Firebases). So it would be great to support that the set of synchronized locations can be time-varying.

**Comment by ThomasWeiser** [comment]
The functionality for Dicts will go to an extra package.
