### ISSUE TITLE
Publish version 1.0.0

### ISSUE THREAD

**Issue by ThomasWeiser** [ThomasWeiser/elmfire#5]
The package has passed [native review](https://github.com/elm-lang/package.elm-lang.org/issues/65) and is now [whitelisted](https://github.com/elm-lang/package.elm-lang.org/pull/75). Thanks to all!

I have changed the API for query options, see [this commit](https://github.com/ThomasWeiser/elmfire/commit/05f8a1c90e208d50d893c3b0ba0a18a27b488607).

So, this is a release candidate for version 1.0.0.

Any comments? @thSoft, @adam-r-kowalski, @vilterp, anybody else?

The code for [syncing dictionaries](/ThomasWeiser/elmfire/issues/4) will likely go to an extra package.

**Comment by thSoft** [comment]
I'm glad this package is approved! I already used it in https://github.com/thSoft/StampTogether so I'm happy with the API. I also support to put the synchronization module in a separate package.

**Comment by ThomasWeiser** [comment]
It's [published](http://package.elm-lang.org/packages/ThomasWeiser/elmfire/latest).
